import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ReactNode } from "react"
import { SidebarProvider } from "@/components/ui/sidebar"
import { Navbar } from "@/components/common/navbar"
import { ThemeProvider } from "@/components/common/theme-provider"
import "./globals.css"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lineage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <Navbar />
            {children}
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}